name: Publish

on:
  push:
    branches:
      - production

permissions:
  contents: write
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: '19.x'
        distribution: 'temurin'
    
    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - run: flutter pub get
    
    - run: flutter build apk

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/app/outputs/apk/release/app-release.apk
        asset_name: stash_installer
        tag: 'latest-apk'
        overwrite: true
        body: "Automatic release"
